Crumbs page added
Warning added as experimental 
Updated info - coin specs
updated paper wallet link for Crumbs
Timer removed for NBX > CRMB swap ratio change
Place holders for CLI, GUI, Swap form
Corrected positioning of timer on mobile 
E.T.R added - Wednesday 22nd May 2019
Download box removed - will be available through GitHub
Swap form removed
Corrected m to M
View only Burn address for NibbleClassic
Burn ratio info removed
In Development images added
Explorer link added
Pool link added
Messaging image added
Crumbs coin specs updated
CLI Download link updated
Link added for About Crumbs
Pool link updated
